spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
    application:
      name: bww-config-bww-dev
---
spring:
  profiles: test
    application:
      name:	asd-config-bww-test  
	  #保存为utf-8格式